const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const clone=x=>x==null?x:structuredClone(x);
const state={settings:{familyOrderEnabled:true},roles:{},users:{'auth-alice':{id:'auth-alice',role:'customer',name:'Alice',phone:'99990000',dni:'0801'},'auth-bob':{id:'auth-bob',role:'customer',name:'Bob',phone:'99990001',dni:'0802'}},products:{p:{id:'p',name:'Tacos',price:119,available:true,modifiers:[]}},familyRooms:{}};
const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state)??null;
const set=(p,x)=>{const a=p.split('/').filter(Boolean),last=a.pop();let v=state;for(const k of a)v=v[k]||={};if(x===null)delete v[last];else v[last]=clone(x)};
const db=async(e,p)=>clone(get(p));
const mutateDb=async(e,p,fn)=>{const next=fn(clone(get(p)));set(p,next);return clone(next)};
const verifyFirebaseUser=async token=>({localId:token,emailVerified:true});
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const context=vm.createContext({crypto:require('node:crypto').webcrypto,URL,Response,console});
vm.runInContext(read('server/family.js').replace('export function','function')+'\nglobalThis.make=createFamily;',context);
const family=context.make({db,mutateDb,verifyFirebaseUser,json});
const call=async(who,input,code='')=>{const request=new Request('https://test.local/api/family'+(code?'?code='+code:''),{method:input?'POST':'GET',headers:{Authorization:'Bearer '+who,'Content-Type':'application/json'},body:input?JSON.stringify(input):undefined});try{return await family.route(request,{})}catch(e){return json({error:e.message},e.status||500)}};
(async()=>{
  let r=await call('alice',{action:'create'});assert.equal(r.status,200);let room=await r.json();assert.match(room.code,/^\d{6}$/);assert.equal(room.members.length,1);
  r=await call('bob',{action:'join',code:room.code});assert.equal(r.status,200);room=await r.json();assert.equal(room.members.length,2);
  r=await call('bob',{action:'add',code:room.code,productId:'p',qty:2,mods:{},note:''});assert.equal(r.status,200);room=await r.json();assert.equal(room.items[0].unit,119);assert.equal(room.items[0].qty,2);assert.equal(room.items[0].ownerName,'Bob');
  assert.equal(JSON.stringify(room).includes('99990001'),false);assert.equal(JSON.stringify(room).includes('0802'),false);
  r=await call('alice',{action:'prepare',code:room.code});assert.equal(r.status,200);
  r=await call('bob',{action:'cancel',code:room.code});assert.equal(r.status,403);
  state.settings.familyOrderEnabled=false;r=await call('alice',null,room.code);assert.equal(r.status,409);
  const app=read('js/app.js'),styles=read('css/styles.css'),worker=read('_worker.js'),access=read('server/access.js'),delivery=read('server/delivery.js'),driver=read('delivery/app.js');
  for(const marker of ['viewChingadazoAI','Chingadazo IA','Mi Perfil Comelón','Círculo familiar','¿Quién paga hoy?','Cultura Chupística','viewChupistica','Pedido Vivo','family_checkout','premium-experience','productImageUrl'])assert.ok(app.includes(marker),marker);
  const home=app.slice(app.indexOf('function viewHome()'),app.indexOf('function viewMenu()'));
  assert.doesNotMatch(home,/smartHomeHtml/);
  assert.match(app,/"live-order": viewLiveOrder/);
  for(const selector of ['.chingadazo-ai-page','.food-profile-page','.premium-passport','.family-page .family-room-head','.premium-family-item','.payer-game-page','.payer-wheel','.chupi-page','.chupi-options','.live-order-page'])assert.ok(styles.includes(selector),selector);
  assert.match(styles,/@media\(max-width:620px\)/);
  assert.ok(worker.includes('family_create')&&worker.includes('live_order_view'));
  assert.match(access,/deliveryCodeRequired/);assert.match(delivery,/El código de entrega no coincide/);assert.match(driver,/Escribe los 4 números/);assert.match(read('js/sync.js'),/familyOrderEnabled/);
  assert.match(app,/no compra viajes ni determina tu nacionalidad/);assert.doesNotMatch(app,/apellido.*ascendencia|ascendencia.*apellido/i);
  assert.doesNotMatch(app,/Costa Caribe/);assert.match(app,/Tu próximo viaje podría ser a/);assert.match(app,/Philly steak/);
  assert.doesNotMatch(app,/Antojo sin fronteras/);assert.doesNotMatch(app,/Tus sugerencias se calculan dentro de El Chingadazo/);
  assert.match(app,/¿En qué se basa este perfil\?/);assert.match(app,/¿Cómo funciona\?/);assert.match(app,/assets\/lempira-3d\.webp/);
  assert.match(app,/assets\/logo\.jpg/);assert.match(app,/Un pedido, varios antojos/);assert.match(app,/Esperando a los aleros/);assert.match(app,/ELIMINAR MI CUENTA/);
  console.log('PASS v106: experiencias 3D, Perfil Comelón, Pasaporte, juegos sociales, pedido en grupo y eliminación protegida.');
})().catch(error=>{console.error(error);process.exitCode=1});
