const assert = require('node:assert/strict');
(async () => {
  const { createSnapshot, verifySnapshot, writeVerifiedBackup } = await import('../server/backups.js');
  const source = { orders: { o1: { total: 125, userId: 'auth-u1' } }, users: { 'auth-u1': { name: 'Prueba', pin: '123456', password: 'private' } }, roles: { u1: 'admin' }, staffPins: { digest: { uid: 'u1' } }, token: 'secret', PIN_PEPPER: 'secret' };
  const snapshot = await createSnapshot(source, '2026-09-28T12:00:00.000Z');
  assert.equal(snapshot.projectId, 'el-chingadazo-cfe45');
  assert.equal(snapshot.data.users['auth-u1'].pin, undefined);
  assert.equal(snapshot.data.token, undefined);
  assert.equal(snapshot.data.PIN_PEPPER, undefined);
  assert.equal(source.users['auth-u1'].pin, '123456', 'Never mutate source');
  assert.deepEqual((await verifySnapshot(snapshot)).orders, source.orders);
  const changed = structuredClone(snapshot); changed.data.orders.o1.total++;
  await assert.rejects(verifySnapshot(changed), /integridad/);
  await assert.rejects(verifySnapshot({ ...snapshot, projectId: 'other' }), /proyecto/);
  await assert.rejects(verifySnapshot({ ...snapshot, createdAt: 'invalid' }), /formato/);
  await assert.rejects(createSnapshot(null), /datos/);
  await assert.rejects(createSnapshot({ text: 'x'.repeat(11 * 1024 * 1024) }), /límite/);
  await assert.rejects(createSnapshot({ accidentalUpload: '-----BEGIN PRIVATE KEY-----\nexample' }), /credenciales/);
  const bookkeeping = await createSnapshot({ backupState: { previous: 'old' }, backupJobs: {}, nested: { refresh_token: 'secret', private_key: 'secret', amount: 40 } });
  assert.equal(bookkeeping.data.backupState, undefined);
  assert.deepEqual(bookkeeping.data.nested, { amount: 40 });
  const objects = new Map();
  const bucket = { put: async (key, value) => objects.set(key, value), get: async key => objects.has(key) ? { text: async () => objects.get(key) } : null };
  const result = await writeVerifiedBackup(bucket, source);
  assert.equal(result.verified, true);
  const restored = await verifySnapshot(JSON.parse(objects.get(result.key)));
  assert.equal(restored.orders.o1.total, 125);
  assert.equal(restored.users[restored.orders.o1.userId].name, 'Prueba');
  assert.equal(restored.roles[restored.staffPins.digest.uid], 'admin');
  await assert.rejects(writeVerifiedBackup(null, source), /configurado/);
  await assert.rejects(writeVerifiedBackup({ put: async () => { throw Error('write failed'); } }, source), /write failed/);
  await assert.rejects(writeVerifiedBackup({ put: async () => {}, get: async () => null }, source), /verificar/);
  await assert.rejects(writeVerifiedBackup({ put: async () => {}, get: async () => ({ text: async () => JSON.stringify(changed) }) }, source), /integridad/);
  await assert.rejects(writeVerifiedBackup({ put: async () => {}, get: async () => ({ text: async () => JSON.stringify(snapshot) }) }, source), /integridad/, 'Valid but stale content must not count as the new backup');
  console.log('PASS backup format, secret exclusion, integrity, isolated recovery, failed writes/readback.');
})().catch(error => { console.error(error); process.exitCode = 1; });
