const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const app=fs.readFileSync('js/app.js','utf8');
 const fixture=new JSDOM('<main><details data-fold="cashConfig"></details><details class="dining-cash"></details><details data-fold="cashPayment" open></details><details data-fold="cashPending"></details></main>');
 const root=fixture.window.document.querySelector('main'),sameView=true;
 const capture=app.match(/const detailsState = ([^;]+);/)[1];
 const detailsState=eval(capture);
 root.querySelector('.dining-cash').remove();
 root.querySelector('[data-fold="cashPayment"]').open=false;
 eval(app.match(/if \(sameView\) \[\.\.\.root\.querySelectorAll\("details[^\n]+/)[0]);
 assert.equal(root.querySelector('[data-fold="cashPayment"]').open,true,'Dynamic dining panel must not shift saved disclosure states');
 assert.equal(root.querySelector('[data-fold="cashPending"]').open,false);
 fixture.window.close();
 const dom=new JSDOM('<section id="cash"></section>',{url:'https://test.local',runScripts:'dangerously'}),w=dom.window;
 w.eval(fs.readFileSync('js/dining-cash.js','utf8'));
 const state={revision:1,consumptionsEnabled:true,tables:{t:{id:'t',number:2,kind:'table'}},accounts:{a:{id:'a',tableId:'t',status:'open',total:189,items:[{name:'Tacos',qty:1,unit:189}]}}};
 let context={},writes=0;
 const host=w.document.querySelector('#cash'),tick=()=>new Promise(r=>setTimeout(r,20));
 const o={user:{id:'a'},api:async(_,opts)=>{if(opts)writes++;return state},getContext:()=>context,getTicket:()=>[],ready:()=>true,setContext:v=>context=v,save:async()=>{},changed:()=>{},getPayment:()=>({shiftId:'s'})};
 w.DiningCash.mount(host,o);await tick();
 let panel=host.querySelector('details.dining-cash');
 assert(panel,'Tables must use a compact disclosure');assert.equal(panel.open,false);
 assert.match(panel.querySelector('summary').textContent,/Mesas en espera.*1/);
 panel.open=true;host.querySelector('[data-cash-open]').click();await tick();
 assert.equal(context.posDiningAccountId,'a');
 assert.match(host.querySelector('summary').textContent,/Mesa 2.*189/);
 assert.equal(writes,0,'Opening a table or panel must not write a sale');
 host.querySelector('[data-cash-checkout]').click();await tick();
 assert.equal(host.querySelector('details').open,true,'Payment confirmation remains visible');
 assert(host.querySelector('[data-cash-confirm]'));
 assert.equal(writes,0,'Displaying payment must not charge');
 w.DiningCash.stop();dom.window.close();
 console.log('PASS compact table disclosure: count, selection, payment visibility and no unintended writes.');
})().catch(e=>{console.error(e);process.exitCode=1});
