const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const clone=x=>x==null?x:structuredClone(x);
const state={roles:{admin:'admin'},drivers:{},orders:{o1:{id:'o1',code:'TT-D1',deliveryCode:'4829',type:'delivery',status:'listo',customerName:'Ana',userId:'auth-c1',phone:'99990000',address:'Colonia Centro, casa 4',addressNotes:'Portón negro',items:[{name:'Torta',qty:1}],total:150,deliveryFee:35,paidAt:'',invoiced:false,deliveryLat:14.08,deliveryLng:-87.20}},deliveries:{},settings:{restaurantLat:14.09,restaurantLng:-87.21,driverPayBase:30,driverPayPerKm:8,driverPayFallback:45}};
const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state)??null;
const set=(p,x)=>{const a=p.split('/').filter(Boolean),last=a.pop();let v=state;for(const k of a)v=v[k]||={};if(x===null)delete v[last];else v[last]=clone(x)};
const db=async(e,p,i)=>{if(i)set(p,i.method==='DELETE'?null:JSON.parse(i.body));return clone(get(p))};
const mutateDb=async(e,p,fn)=>{const next=fn(clone(get(p)));set(p,next);return clone(next)};
const users={admin:{localId:'admin',email:'owner@test',emailVerified:true},d1:{localId:'d1',email:'d1@test',emailVerified:true},d2:{localId:'d2',email:'d2@test',emailVerified:true},c1:{localId:'c1',email:'c1@test',emailVerified:true}};
const verifyFirebaseUser=async t=>users[t]||Promise.reject(Error('bad'));
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json'}});
const ctx=vm.createContext({crypto:require('node:crypto').webcrypto,Response,URL,console,Math,Date});
vm.runInContext(read('server/delivery.js').replace('export function','function')+'\nglobalThis.create=createDelivery;',ctx);
let awarded=[],uploaded=[];
const delivery=ctx.create({db,mutateDb,verifyFirebaseUser,json,readBody:r=>r.json(),uploadDocument:async(e,name)=>uploaded.push(name),readDocument:async(e,name)=>new Response(name),computeRoute:async(e,a,b)=>({distanceKm:2,durationMin:8,polyline:'abc'}),awardOrder:async(e,o)=>awarded.push(o.id)});
const req=(who,method='GET',data,url='https://test/api')=>new Request(url,{method,headers:{Authorization:'Bearer '+who,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
async function rejected(p,status){try{await p;assert.fail('Expected rejection')}catch(e){assert.equal(e.status,status,e.message)}}
(async()=>{
 const profile={name:'Driver Uno',dni:'0801199912345',phone:'99991111',residenceAddress:'Casa 1',residenceReference:'Portón azul',licenseNumber:'LIC-1',licenseExpires:'2099-01-01',vehicleType:'Moto',vehiclePlate:'ABC123',vehicleVin:'1HGCM82633A004352',vehicleRightObject:'drivers/d1/vehicle-right.jpg',vehicleLeftObject:'drivers/d1/vehicle-left.jpg',vinObject:'drivers/d1/vin.jpg',selfieObject:'drivers/d1/selfie.jpg',licenseObject:'drivers/d1/license.jpg',consent:'on'};
 let r=await delivery.profile(req('d1','POST',profile),{});assert.equal(r.status,200);assert.equal(state.roles.d1,'driver_pending');assert.equal(state.drivers['auth-d1'].selfieObject,'drivers/d1/selfie.jpg');
 await rejected(delivery.orders(req('d1'),{}),403);
 await delivery.admin(req('admin','POST',{action:'approve',driverId:'auth-d1'}),{});assert.equal(state.roles.d1,'driver');
 await delivery.admin(req('admin','POST',{action:'photo_requirement',driverId:'auth-d1',required:true}),{});assert.equal(state.drivers['auth-d1'].requireDeliveryPhoto,true);
 await delivery.admin(req('admin','POST',{action:'settings',restaurantAddress:'El Chingadazo',lat:14.09,lng:-87.21,driverPayBase:30,driverPayPerKm:8,driverPayFallback:45,deliveryCustomerFee1:30,deliveryCustomerFee3:35,deliveryCustomerFee65:75,deliveryCustomerFee8:110,deliveryCustomerMaxKm:5000,blockedDeliveryZones:''}),{});assert.equal(state.settings.deliveryCustomerMaxKm,5000);
 state.drivers['auth-d2']={...state.drivers['auth-d1'],id:'auth-d2',authUid:'d2',name:'Driver Dos'};state.roles.d2='driver';
 state.settings.deliveryPricingUpdatedAt='pricing-v2';
 state.deliveries.o1={id:'o1',orderId:'o1',status:'available',driverPay:0,distanceKm:0,pricingVersion:'pricing-v1'};
 r=await delivery.orders(req('d1'),{});let data=await r.json();assert.equal(data.available.length,1);assert.equal(data.available[0].address,undefined);assert.equal(data.available[0].phone,undefined);
 assert.equal(data.available[0].driverPay,35);assert.equal(state.deliveries.o1.pricingVersion,'pricing-v2');
 state.orders.o1.status='preparacion';
 r=await delivery.orders(req('d1'),{});data=await r.json();assert.equal(data.available.some(x=>x.id==='o1'),true,'Administración puede recibir la orden sin apagar la oferta del repartidor');
 state.orders.o1.status='listo';
 r=await delivery.accept(req('d1','POST',{orderId:'o1',location:{lat:14.1,lng:-87.22}}),{});data=await r.json();assert.equal(data.job.address,'Colonia Centro, casa 4');assert.equal(state.deliveries.o1.driverId,'auth-d1');assert.equal(state.deliveries.o1.driverPay,35);assert.equal(state.orders.o1.status,'listo');assert.equal(state.orders.o1.receivedAt,undefined);
 await rejected(delivery.accept(req('d2','POST',{orderId:'o1',location:{lat:14.1,lng:-87.22}}),{}),409);
 await delivery.location(req('d1','POST',{orderId:'o1',lat:14.1,lng:-87.22,accuracy:5}),{});
 const fixTime=Date.now();
 await delivery.location(req('d1','POST',{orderId:'o1',lat:14.1,lng:-87.22,accuracy:5,capturedAt:fixTime}),{});
 await delivery.location(req('d1','POST',{orderId:'o1',lat:14.2,lng:-87.23,accuracy:5,capturedAt:fixTime-1000}),{});
 assert.equal(state.deliveries.o1.location.lat,14.1);
 await rejected(delivery.location(req('d1','POST',{orderId:'o1',lat:14.1,lng:-87.22,accuracy:500,capturedAt:fixTime}),{}),400);
 await rejected(delivery.location(req('d1','POST',{orderId:'o1',lat:14.1,lng:-87.22,accuracy:5,capturedAt:fixTime-60000}),{}),400);
 await rejected(delivery.location(req('d1','POST',{orderId:'o1',lat:null,lng:-87.22,accuracy:5}),{}),400);
 r=await delivery.track(req('c1'),{},'o1');data=await r.json();assert.equal(data.location,null);
 await delivery.status(req('d1','POST',{orderId:'o1',status:'heading_pickup',pickupEtaMin:7}),{});
 await rejected(delivery.status(req('d1','POST',{orderId:'o1',status:'picked_up'}),{}),409);assert.equal(state.orders.o1.status,'listo');
 state.orders.o1.invoiced=true;state.orders.o1.paidAt=new Date().toISOString();
 await delivery.status(req('d1','POST',{orderId:'o1',status:'picked_up'}),{});assert.equal(state.orders.o1.status,'camino');
 r=await delivery.track(req('c1'),{},'o1');data=await r.json();assert.equal(data.location.lat,14.1);
 await rejected(delivery.status(req('d1','POST',{orderId:'o1',status:'delivered'}),{}),409);
 const proofUrl=new URL('https://test/api/delivery/document?kind=proof&orderId=o1');
 const proofReq=new Request(proofUrl,{method:'POST',headers:{Authorization:'Bearer d1','Content-Type':'image/jpeg'},body:new Uint8Array([1,2,3])});
 await delivery.documentUpload(proofReq,{},proofUrl);assert.equal(state.deliveries.o1.proofObject.startsWith('deliveries/o1/d1/proof-'),true);assert.equal(uploaded.length,1);
 await rejected(delivery.status(req('d1','POST',{orderId:'o1',status:'delivered',deliveryCode:'0000'}),{}),409);
 await delivery.status(req('d1','POST',{orderId:'o1',status:'delivered',deliveryCode:'4829'}),{});assert.equal(state.orders.o1.status,'entregado');assert.deepEqual(awarded,['o1']);
 r=await delivery.proofRead(req('admin'),{},'o1');assert.match(await r.text(),/deliveries\/o1\/d1\/proof-/);
 r=await delivery.rating(req('c1','POST',{orderId:'o1',score:5,note:'Excelente'}),{});data=await r.json();assert.equal(data.rating.emoji,'😍');
 assert.equal(data.rating.score,5);
 assert.equal(data.rating.note,'Excelente');
 assert.equal(state.orders.o1.deliveryRating.score,5);
 r=await delivery.orders(req('d1'),{});data=await r.json();assert.equal(data.history.length,1);assert.equal(data.history[0].id,'o1');
 state.orders.o2={...state.orders.o1,id:'o2',code:'TT-D2',status:'listo',paidAt:'',invoiced:false};
 state.deliveries.o2={id:'o2',orderId:'o2',status:'available',driverPay:45,distanceKm:2,pricingVersion:state.settings.deliveryPricingUpdatedAt};
 await delivery.rejectOffer(req('d2','POST',{orderId:'o2'}),{});
 r=await delivery.orders(req('d2'),{});data=await r.json();assert.equal(data.available.some(x=>x.id==='o2'),false);
 r=await delivery.orders(req('d1'),{});data=await r.json();assert.equal(data.available.some(x=>x.id==='o2'),true);
 state.orders.o3={...state.orders.o1,id:'o3',code:'TT-D3',status:'entregado',paidAt:'',invoiced:false,deliveredAt:'old'};
 state.deliveries.o3={id:'o3',orderId:'o3',status:'accepted',driverId:'auth-d1',driverName:'Driver Uno',driverPay:45,distanceKm:2};
 await delivery.orders(req('d1'),{});assert.equal(state.orders.o3.status,'listo');assert.equal(state.orders.o3.deliveredAt,'');
 await rejected(delivery.track(req('d2'),{},'o1'),403);
 console.log('PASS delivery: aprobación, privacidad, aceptación atómica, GPS, cobro, historial, rechazo y reparación.');
})().catch(e=>{console.error(e);process.exitCode=1});
