const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','server/access.js'),'utf8').replace('export function','function')+'\nglobalThis.create=createAccess;';
const state={products:{p1:{id:'p1',name:'Torta',price:100,available:true,modifiers:[],image:'media:p1'}},settings:{restaurantLat:14.08,restaurantLng:-87.2,deliveryCustomerFee1:30,deliveryCustomerFee3:35,deliveryCustomerFee65:75,deliveryCustomerFee8:110,deliveryCustomerMaxKm:8,deliveryNationwideTestEnabled:false,deliveryFixedZoneEnabled:true,deliveryFixedZoneName:'Zona por configurar',deliveryFixedZoneFee:35},users:{'auth-c1':{id:'auth-c1',role:'customer',name:'Ana',phone:'99990000',dni:'0801199012345',points:0}},orders:{}};
const clone=x=>x==null?x:structuredClone(x),get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state)??null;
const set=(p,x)=>{const a=p.split('/').filter(Boolean),last=a.pop();let v=state;for(const k of a)v=v[k]||={};v[last]=clone(x)};
const db=async(e,p,i)=>{if(i)set(p,JSON.parse(i.body));return clone(get(p))};
const mutateDb=async(e,p,fn)=>{const next=fn(clone(get(p)));set(p,next);return clone(next)};
const ctx=vm.createContext({crypto:require('node:crypto').webcrypto,Response,URL,console,Intl,Math,Date});vm.runInContext(source,ctx);
const make=distance=>ctx.create({db,mutateDb,verifyFirebaseUser:async()=>({localId:'c1',email:'a@test',emailVerified:true}),json:(x,s=200)=>new Response(JSON.stringify(x),{status:s}),computeRoute:async()=>({distanceKm:distance,durationMin:10,polyline:'route'})});
const auth={id:'auth-c1',role:'customer',user:{localId:'c1',email:'a@test',emailVerified:true}};
const input={items:[{productId:'p1',qty:1,mods:{}}],type:'delivery',address:'Colonia segura',addressNotes:'Casa 1',deliveryAccuracy:15,deliveryLat:14.09,deliveryLng:-87.21,payment:'Efectivo',tip:20,total:0};
(async()=>{
  let access=make(2),order=await access.createOrder({},auth,'o1',input);
  assert.equal(order.deliveryFee,35);assert.equal(order.tip,20);assert.equal(order.total,155);assert.equal(order.pointsEarned,10);assert.equal(order.items[0].image,'/api/media/p1');
  state.settings.blockedDeliveryZones='zona bloqueada';
  await assert.rejects(()=>access.createOrder({},auth,'o2',{...input,address:'Zona bloqueada, casa 2'}),e=>e.status===409);
  state.settings.blockedDeliveryZones='';access=make(9);
  await assert.rejects(()=>access.createOrder({},auth,'o3',input),e=>e.status===409);
  access=make(2);
  await assert.rejects(()=>access.createOrder({},auth,'o3-gps',{...input,deliveryAccuracy:2000}),e=>e.status===409);
  state.settings.deliveryNationwideTestEnabled=true;access=make(320);
  await assert.rejects(()=>access.createOrder({},auth,'o3-test-bad',{...input,deliveryAccuracy:2000}),e=>e.status===409);
  await assert.rejects(()=>access.createOrder({},auth,'o3-test-old',{...input,deliveryCapturedAt:Date.now()-600000}),e=>e.status===409);
  await assert.rejects(()=>access.createOrder({},auth,'o3-test-empty',{...input,deliveryLat:''}),e=>e.status===400);
  order=await access.createOrder({},auth,'o3-test',{...input,address:'Copán Ruinas, Honduras'});
  assert.equal(order.deliveryFee,110);assert.equal(order.deliveryDistanceKm,320);assert.equal(order.deliveryPricingMode,'nationwide_test');assert.equal(order.deliveryZoneName,'Honduras · modo de pruebas');
  access=make(4.8);order=await access.createOrder({},auth,'o4',{...input,address:'Zona por configurar, casa 12',deliveryZoneId:'altos-chingadazo'});
  assert.equal(order.deliveryFee,35);assert.equal(order.deliveryDistanceKm,4.8);assert.equal(order.deliveryPricingMode,'fixed_zone');assert.equal(order.deliveryZoneName,'Zona por configurar');
  const noRoute=ctx.create({db,mutateDb,verifyFirebaseUser:async()=>({localId:'c1',email:'a@test',emailVerified:true}),json:(x,s=200)=>new Response(JSON.stringify(x),{status:s}),computeRoute:async()=>null});
  order=await noRoute.createOrder({},auth,'o5',{...input,deliveryLat:15.5,deliveryLng:-88.03,address:'San Pedro Sula, Honduras'});
  assert.equal(order.deliveryFee,110);assert.equal(order.deliveryPricingMode,'nationwide_test');assert.equal(order.deliveryDistanceSource,'air_distance_test');
  state.settings.deliveryNationwideTestEnabled=false;
  await assert.rejects(()=>noRoute.createOrder({},auth,'o6',input),e=>e.status===503);
  console.log('PASS delivery fees: ruta Google, zona fija L.35, propina, zonas, radio máximo y modo nacional de pruebas.');
})().catch(e=>{console.error(e);process.exitCode=1});
