const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),clone=x=>x==null?x:structuredClone(x);
const state={roles:{},users:{'auth-alice':{id:'auth-alice',role:'customer',name:'Alice Catracha',phone:'99990000',dni:'0801'},'auth-bob':{id:'auth-bob',role:'customer',name:'Bob Catracho',phone:'99990001',dni:'0802'},'auth-carol':{id:'auth-carol',role:'customer',name:'Carol',phone:'99990002',dni:'0803'}},payerGames:{}};
const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state)??null;
const set=(p,x)=>{const a=p.split('/').filter(Boolean),last=a.pop();let v=state;for(const k of a)v=v[k]||={};if(x===null)delete v[last];else v[last]=clone(x)};
const db=async(e,p)=>clone(get(p));
const mutateDb=async(e,p,fn)=>{const next=fn(clone(get(p)));set(p,next);return clone(next)};
const verifyFirebaseUser=async token=>({localId:token,emailVerified:true});
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const context=vm.createContext({crypto:require('node:crypto').webcrypto,URL,Response,console});
vm.runInContext(read('server/payer-game.js').replace('export function','function')+'\nglobalThis.make=createPayerGame;',context);
const game=context.make({db,mutateDb,verifyFirebaseUser,json});
const call=async(who,input,code='')=>{const request=new Request('https://test.local/api/payer-game'+(code?'?code='+code:''),{method:input?'POST':'GET',headers:{Authorization:'Bearer '+who,'Content-Type':'application/json'},body:input?JSON.stringify(input):undefined});try{return await game.route(request,{})}catch(e){return json({error:e.message},e.status||500)}};
(async()=>{
  let r=await call('alice',{action:'create'});assert.equal(r.status,200);let room=await r.json();assert.match(room.code,/^\d{6}$/);assert.equal(room.members.length,1);
  r=await call('bob',{action:'join',code:room.code});assert.equal(r.status,200);room=await r.json();assert.equal(room.members.length,2);
  assert.equal(JSON.stringify(room).includes('99990001'),false);assert.equal(JSON.stringify(room).includes('0802'),false);
  r=await call('bob',{action:'draw',code:room.code});assert.equal(r.status,403);
  r=await call('alice',{action:'draw',code:room.code});assert.equal(r.status,200);room=await r.json();assert.equal(room.status,'spinning');assert.equal(room.winner,null);assert.equal(room.spin.durationMs,6500);assert.ok(room.spin.rotationDeg>=2160);assert.equal(JSON.stringify(room).includes('auth-alice'),false);
  const aliceSpin=room.spin;r=await call('bob',null,room.code);const bobView=await r.json(),bobSpin=bobView.spin;assert.equal(bobView.status,'spinning');assert.equal(bobView.isOrganizer,false);assert.equal(bobSpin.startedAt,aliceSpin.startedAt);assert.equal(bobSpin.endsAt,aliceSpin.endsAt);assert.equal(bobSpin.rotationDeg,aliceSpin.rotationDeg);
  const app=read('js/app.js'),styles=read('css/styles.css');assert.match(app,/synced-spinning/);assert.match(app,/data-payer-refresh/);assert.match(styles,/payer-synced-spin/);
  state.payerGames[room.code].spinEndsAt=new Date(Date.now()-10).toISOString();
  r=await call('bob',null,room.code);room=await r.json();assert.equal(room.status,'drawn');assert.ok(room.members.map(m=>m.id).includes(room.winner.id));const winner=room.winner.id;
  r=await call('alice',null,room.code);assert.equal((await r.json()).winner.id,winner);
  r=await call('carol',{action:'join',code:room.code});assert.equal(r.status,409);
  r=await call('alice',{action:'new_round',code:room.code});assert.equal(r.status,200);room=await r.json();assert.equal(room.status,'open');assert.equal(room.round,2);assert.equal(room.winner,null);
  r=await call('bob',{action:'leave',code:room.code});assert.equal(r.status,200);room=await r.json();assert.equal(room.members.length,1);
  console.log('PASS v106: organizador e invitados ven el mismo giro sincronizado, resultado único, permisos, privacidad y nuevas rondas.');
})().catch(error=>{console.error(error);process.exitCode=1});
