const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const read = f => fs.readFileSync(path.join(__dirname, '..', f), 'utf8');
(async () => {
  const ctx = vm.createContext({window:{},AbortController,setTimeout,clearTimeout,fetch: async url => new Response(JSON.stringify(url.includes('/orders.json') ? {} : url.includes('/products.json') ? {banana:{id:'banana', image:'media:banana'}} : {}), {status:url.includes('/orders.json') ? 403 : 200})});
  vm.runInContext(read('js/sync.js') + '\nglobalThis.cloud = Cloud;', ctx);
  assert.equal(ctx.window.Cloud, ctx.cloud);
  const result = await ctx.cloud.pull();
  assert.equal(result.products[0].id, 'banana');
  assert.equal(result.orders.length, 0);
  console.log('PASS catálogo disponible aunque fallen órdenes');
  const w = vm.createContext({Response, crypto:require('node:crypto').webcrypto});
  vm.runInContext(read('server/access.js').replace('export function','function'),w);
  w.createDelivery=()=>({});
  w.createFamily=()=>({route:async()=>new Response('{}')});
  w.createPayerGame=()=>({route:async()=>new Response('{}')});
  w.createChupisticaGame=()=>({route:async()=>new Response('{}')});
  w.createManager=()=>({recordSale:async()=>({})});
  Object.assign(w,await import('../server/shift-maintenance.js'),await import('../server/instance.js'));
  vm.runInContext(read('_worker.js').replace(/^(?:import .*\n)+/,'').replace('export default {', 'globalThis.worker = {'), w);
  vm.runInContext(`globalThis.role='cashier'; globalThis.saved={promos:[{id:'old',title:'Conservar'}],blasts:[]};
    verifyFirebaseUser=async()=>({localId:'test'});
    db=async(env,path,init)=>init ? (globalThis.bonus=JSON.parse(init.body)) : role;
    mutateDb=async(env,path,fn)=>{saved=fn(saved)};
    body=async request=>request.data;
    globalThis.run=data=>savePromotion({headers:{get:()=> 'Bearer test'},data},{});`,w);
  assert.equal((await w.run({kind:'bonus',value:0})).status,403);
  w.role='admin';
  assert.equal((await w.run({kind:'bonus',value:0})).status,200);
  assert.equal(w.bonus,0);
  assert.equal((await w.run({kind:'bonus',value:-1})).status,400);
  await w.run({kind:'promo',id:'new',title:'Nueva',body:'Detalle'});
  assert.equal(w.saved.promos.length,2);
  await w.run({kind:'promo',id:'new',title:'Editada',body:'Detalle'});
  assert.equal(w.saved.promos.length,2);
  assert.equal(w.saved.promos[1].title,'Editada');
  assert.equal(w.saved.blasts.length,0);
  await assert.rejects(()=>w.run({kind:'promo',title:'<script>',body:'x'}));
  console.log('PASS rol requerido, bono cero, límites, edición sin duplicados ni avisos y rechazo HTML');
  const app=read('js/app.js'),sync=read('js/sync.js'),worker=read('_worker.js');
  assert.match(app,/Órdenes de la app por facturar/);
  assert.doesNotMatch(app,/Pedidos app por enviar a caja/);
  assert.doesNotMatch(app,/data-cashier-queue=/);
  assert.match(sync,/async function invoiceOrder\(/);
  assert.match(worker,/\/api\/invoice-order/);
  console.log('PASS una sola cola de facturación y cobro atómico por servidor');
  const ops=read('js/ops.js');
  assert.match(ops,/o\.invoiced === true && o\.paidAt/);
  assert.match(ops,/filter\(isRevenueOrder\)/);
  console.log('PASS reportes contables incluyen únicamente órdenes pagadas y facturadas');
  assert.match(worker,/env\.DRIVER_DOCS\.put/);
  assert.match(worker,/env\.DRIVER_DOCS\.get/);
  assert.doesNotMatch(worker,/storage\.googleapis\.com/);
  assert.match(read('wrangler.jsonc'),/"binding": "DRIVER_DOCS"/);
  console.log('PASS documentos privados de repartidores usan Cloudflare R2');
  const driverApp=read('delivery/app.js');
  assert.match(driverApp,/repartidor\.demo@el-chingadazo\.invalid/);
  assert.match(driverApp,/data-action="demo-login"/);
  assert.doesNotMatch(driverApp,/DEMO_PASSWORD/);
  assert.match(driverApp,/Ninguna acción modifica pedidos reales/);
  assert.match(driverApp,/if\s*\(state\.demo\)\s*demoAccept/);
  assert.match(driverApp,/if\s*\(state\.demo\)\s*demoStatus/);
  assert.match(driverApp,/enhanceForms/);
  assert.match(driverApp,/submit\.type\s*=\s*"submit"/);
  assert.match(driverApp,/data-action="demo-login"/);
  assert.match(app,/deliverySettingsDraft/);
  assert.match(app,/captureDeliverySettingsDraft/);
  assert.match(app,/#welcomeBonusForm, #deliverySettingsForm/);
  assert.match(read('server/delivery.js'),/deliveryPricingUpdatedAt/);
  assert.match(read('delivery/sw.js'),/chingadazo-delivery-v123/);
  console.log('PASS demo aislado, tarifas recalculables y caché v107');
  assert.match(app,/customerSearchForm/);
  assert.match(app,/category-buttons/);
  assert.match(app,/floating-cart/);
  assert.match(app,/data-menu-item/);
  assert.match(read('css/styles.css'),/Experiencia cliente v84/);
  console.log('PASS interfaz cliente v84: búsqueda, categorías visibles, tarjetas y carrito flotante');
  assert.match(app,/Populares del Chingadazo/);
  assert.match(app,/cart-attention/);
  assert.match(read('css/styles.css'),/\.cart-added-toast[^}]*pointer-events:none/);
  assert.doesNotMatch(read('css/styles.css'),/\}\.cart-attention-done\{/);
  assert.doesNotMatch(app,/querySelectorAll\("\.cart-attention,\.cart-added-toast"\)/);
  assert.match(read('server/delivery.js'),/\["picked_up", "delivered"\]/);
  assert.match(read('server/delivery.js'),/hasCustomerFee/);
  assert.match(app,/TRAPIPUNTOS/);
  assert.match(app,/syncCompletedDeliveryRatings/);
  assert.match(read('css/styles.css'),/Experiencia cliente v85/);
  assert.match(read('sw.js'),/chingadazo-v131/);
  assert.match(read('js/app.js'),/beforeinstallprompt/);
  assert.match(read('server/push.js'),/audience:"staff"/);
  assert.match(read('server/push.js'),/audience:"customers"/);
  assert.match(read('delivery/app.js'),/Sonido y push activos/);
  assert.match(app,/Envío dentro de Zona por configurar/);
  assert.match(app,/requestDeliveryQuote/);
  assert.match(read('server/access.js'),/nationwideTest/);
  assert.match(read('server/access.js'),/pricingMode:fixedZone\?'fixed_zone':\(nationwideTest\?'nationwide_test':'google_route'\)/);
  assert.match(app,/Modo de pruebas: permitir pedidos sin límite de kilómetros/);
  assert.match(app,/nationwideDeliveryTestEnabled/);
  assert.match(app,/maximumAccuracy = 100/);
  assert.match(read('server/access.js'),/deliveryAccuracy>100/);
  assert.match(driverApp,/notificationPermission/);
  assert.doesNotMatch(driverApp,/state\.soundEnabled\s*&&\s*Notification\.permission/);
  assert.match(app,/Entregada al repartidor · va al cliente/);
  assert.match(read('server/push.js'),/async function test/);
  assert.match(read('server/push.js'),/UNREGISTERED/);
  assert.match(worker,/\/api\/delivery\/push-test/);
  assert.match(worker,/\/api\/push-test/);
  assert.match(worker,/\/api\/analytics\/event/);
  assert.match(worker,/\/api\/analytics\/report/);
  assert.match(worker,/Conteos agregados/);
  assert.match(app,/medición no guarda nombres, correos, DNI, teléfonos, direcciones ni ubicaciones/);
  assert.match(app,/trackFunnel\("order_complete"\)/);
  assert.match(app,/Conversión de la app/);
  assert.doesNotMatch(app,/await Cloud\.pullMedia\(\)/);
  assert.match(app,/loading="lazy" decoding="async"/);
  assert.doesNotMatch(worker,/analytics.*(?:dni|email|phone|address)/i);
  assert.match(driverApp,/deliveryServiceWorker/);
  assert.match(app,/appServiceWorker/);
  assert.doesNotMatch(read('sw.js'),/keys\.map\(\(k\) => caches\.delete/);
  assert.match(worker,/await push\.notifyCustomers/);
  assert.match(worker,/push: pushResult/);
  const pushSetup=read('CONFIGURAR-NOTIFICACIONES-PUSH.bat');
  assert.match(pushSetup,/OpenFileDialog/);
  assert.match(pushSetup,/configure-firebase-push\.mjs/);
  assert.doesNotMatch(pushSetup,/Pega en una sola linea/);
  assert.match(read('REPARAR-CUENTA-SERVICIO-PUSH.bat'),/configure-firebase-push\.mjs/);
  const validator=read('scripts/configure-firebase-push.mjs');
  assert.match(validator,/service_account/);
  assert.match(validator,/FIREBASE_SERVICE_ACCOUNT_JSON/);
  assert.match(validator,/crypto\.sign/);
  assert.match(validator,/oauth2|token_uri/);
  assert.match(validator,/fcm\.googleapis\.com/);
  assert.match(validator,/assertInstance/);
  assert.match(validator,/urn:ietf:params:oauth:grant-type:jwt-bearer/);
  assert.doesNotMatch(validator,/urn:ietf:params:oauth2:grant-type/);
  assert.match(validator,/process\.env\.ComSpec\|\|"cmd\.exe"/);
  assert.match(validator,/npx\.cmd wrangler@latest secret put FIREBASE_SERVICE_ACCOUNT_JSON/);
  assert.match(read('server/push.js'),/urn:ietf:params:oauth:grant-type:jwt-bearer/);
  assert.doesNotMatch(read('server/push.js'),/urn:ietf:params:oauth2:grant-type/);
  assert.match(read('server/delivery.js'),/requireDeliveryPhoto/);
  assert.match(read('server/delivery.js'),/proofObject/);
  assert.match(read('_worker.js'),/cashReceivedFrom/);
  console.log('PASS interfaz v107: caja delivery, foto opcional, OAuth, push, estados, GPS de pruebas, ruta nacional, conversión y cachés aisladas');
})().catch(e=>{console.error(e);process.exitCode=1});
