const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const clone=x=>structuredClone(x);
// Keep the scheduled-order assertions away from the Honduras midnight boundary.
const Date=class extends global.Date {constructor(...args){super(...(args.length?args:['2026-10-02T18:00:00Z']));}static now(){return global.Date.parse('2026-10-02T18:00:00Z');}};
const state={roles:{admin:'admin',cash:'cashier',cook:'kitchen'},users:{'auth-alice':{id:'auth-alice',role:'customer',name:'Alice',phone:'99990000',dni:'0801199012345',addresses:[{id:'a',line:'Calle 1'}],points:2200},'auth-bob':{id:'auth-bob',role:'customer',name:'Bob',password:'DO-NOT-LEAK'},'auth-cash':{id:'auth-cash',role:'cashier'}},orders:{},shifts:{s1:{id:'s1',userId:'auth-cash'}},products:{p:{id:'p',name:'Torta',price:100,available:true,modifiers:[{id:'salsa',name:'Salsa',required:true,options:[{id:'bbq',name:'BBQ',price:10}]}]}},settings:{welcomeBonus:500,taxRate:0,deliveryFee:0}};
const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state) ?? null;
const set=(p,x)=>{const parts=p.split('/').filter(Boolean),last=parts.pop();let v=state;for(const k of parts)v=v[k] ||= {};if(x===null)delete v[last];else v[last]=clone(x);};
const db=async(e,p,i)=>{if(i){set(p,i.method==='DELETE'?null:JSON.parse(i.body));}return clone(get(p));};
const mutateDb=async(e,p,fn)=>{const next=fn(clone(get(p)));set(p,next);return clone(next);};
const verifyFirebaseUser=async token=>{if(token==='invalid')throw Error('bad');return {localId:token,email:token+'@example.test',emailVerified:token!=='unverified'};};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const context=vm.createContext({crypto:require('node:crypto').webcrypto,URL,Response,console,Date});
vm.runInContext(read('server/access.js').replace('export function','function')+'\nglobalThis.create=createAccess;',context);
const access=context.create({db,mutateDb,verifyFirebaseUser,json});
async function call(who,node,method='GET',data,headers={}){
 const r=new Request('https://test.local/api/data/'+node,{method,headers:{...(who?{Authorization:'Bearer '+who}:{}),...headers},body:data===undefined?undefined:JSON.stringify(data)});
 try{return await access.route(r,{});}catch(e){return json({error:e.message},e.status || 500);}
}
async function status(who,node,method,data,expected){const r=await call(who,node,method,data);assert.equal(r.status,expected,await r.text());}
(async()=>{
 assert.deepEqual(JSON.parse(read('firebase-rules.production.json')),{rules:{'.read':false,'.write':false}});
 assert.equal((await call(null,'products')).status,200);
 await status(null,'users','GET',undefined,401);
 await status(null,'orders','GET',undefined,401);
 await status(null,'shifts','GET',undefined,401);
 await status(null,'products/p','PUT',{},401);
 await status('alice','roles/alice','PUT','admin',403);
 await status('alice','users/auth-bob','GET',undefined,403);
 await status('alice','staffPins','GET',undefined,403);
 await status('alice','financeConfig','GET',undefined,403);
 await status('alice','financeConfig','PUT',{fx:1},403);
 await status('cook','shifts/s1','PUT',{},403);
 const own=await (await call('alice','users')).json();assert.deepEqual(Object.keys(own),['auth-alice']);
 const all=await (await call('admin','users')).json();assert.equal(all['auth-bob'].password,undefined);
 await status('alice','users/auth-alice','PUT',{name:'Alice',role:'admin',points:999999,password:'bad'},200);
 assert.equal(state.users['auth-alice'].points,2200);assert.equal(state.users['auth-alice'].role,'customer');
 for(const dni of ['080119901234','08011990123456','A801199012345'])await status('alice','users/auth-alice','PUT',{dni},400);
 for(const phone of ['9999000','999900000','99990000A'])await status('alice','users/auth-alice','PUT',{phone},400);
 await status('alice','users/auth-alice','PUT',{dni:'0801-1990-12345',phone:'+504 9999-0000'},200);
 assert.equal(state.users['auth-alice'].dni,'0801199012345');assert.equal(state.users['auth-alice'].phone,'99990000');assert.equal(state.users['auth-alice'].points,2200);
 const order={items:[{productId:'p',qty:1,mods:{salsa:'bbq'}}],total:110,payment:'Tarjeta',address:'Calle 1'};
 const savedDni=state.users['auth-alice'].dni;
 state.users['auth-alice'].dni='080119901234';await status('alice','orders/invalid-profile','PUT',order,400);assert.equal(state.orders['invalid-profile'],undefined);state.users['auth-alice'].dni=savedDni;
 await status('alice','orders/o1','PUT',{...order,total:1},409);
 await status('alice','orders/o1','PUT',{...order,paidAt:'fake',userId:'auth-bob',invoiced:true,paymentChannel:'online',gatewayPayment:{verified:true,status:'captured',transactionId:'fake'}},200);
 assert.equal(state.orders.o1.userId,'auth-alice');assert.equal(state.orders.o1.invoiced,false);assert.equal(state.orders.o1.paidAt,'');assert.equal(state.orders.o1.paymentChannel,undefined);assert.equal(state.orders.o1.gatewayPayment,undefined);
 await status('bob','orders/o1','GET',undefined,403);
 await status('bob','orders/o1','PUT',order,403);
 const customerOrders=await (await call('bob','orders')).json();assert.deepEqual(customerOrders,{});
 state.orders.old={...clone(state.orders.o1),id:'old',createdAt:new Date(Date.now()-86400000).toISOString()};
 state.orders.due={...clone(state.orders.o1),id:'due',status:'programado',scheduledFor:new Date(Date.now()-1000).toISOString()};
 state.orders.future={...clone(state.orders.o1),id:'future',status:'programado',scheduledFor:new Date(Date.now()+3600000).toISOString()};
 const kitchen=await (await call('cook','orders')).json();assert.equal(kitchen.o1.dni,undefined);
 assert.equal(kitchen.old,undefined);assert.equal(kitchen.due.status,'nuevo');assert.equal(kitchen.future.status,'programado');
 const adminOrders=await (await call('admin','orders')).json();assert.equal(adminOrders.old.id,'old');
 await status('cook','orders/o1','PUT',{...state.orders.o1,invoiced:true},403);
 await status('cash','orders/zeroNew','PUT',{...order,payment:'Efectivo',paidAt:'yes',shiftId:'s1',payWith:0},400);
 assert.equal(state.orders.zeroNew,undefined);
 state.orders.zeroCash={...clone(state.orders.o1),id:'zeroCash',payment:'Efectivo',payWith:200};
 await status('cash','orders/zeroCash','PUT',{...state.orders.zeroCash,payment:'Efectivo',paidAt:'yes',shiftId:'s1',payWith:0},400);
 assert.equal(state.orders.zeroCash.paidAt,'');
 state.orders.archived={id:'archived',status:'cancelado',testArchivedAt:'2026-09-24'};
 await status('cash','orders/archived','PUT',order,409);
 await status('admin','orders/archived','GET',undefined,403);
 assert.equal((await (await call('admin','orders')).json()).archived,undefined);
 await status('alice','operationArchives','GET',undefined,403);
 const snapshot=clone(state.orders.o1),etag=(await call('cash','orders/o1')).headers.get('etag');
 const invoice={...snapshot,paidAt:'yes',invoiced:true,shiftId:'s1'};
 assert.equal((await call('cash','orders/o1','PUT',invoice,{'if-match':etag})).status,200);
 assert.equal(state.orders.o1.paymentChannel,'pos');assert.equal(state.orders.o1.paidBy,'auth-cash');assert.equal(state.orders.o1.invoiced,true);
 assert.equal((await call('cash','orders/o1','PUT',invoice,{'if-match':etag})).status,412);
 await status('cash','orders/o1','PUT',{...state.orders.o1,total:1},409);
 state.orders.o1.status='entregado';await access.award({},state.orders.o1);await access.award({},state.orders.o1);
 assert.equal(state.users['auth-alice'].points,2210);
 state.orders.deliveryPoints={...clone(state.orders.o1),id:'deliveryPoints',type:'delivery',status:'entregado',invoiced:true,paidAt:'yes',pointsEarned:20};
 await access.award({},state.orders.deliveryPoints);await access.award({},state.orders.deliveryPoints);
 assert.equal(state.users['auth-alice'].points,2230);
 await status('new','users/auth-new','PUT',{name:'New',phone:'99990001',dni:'0801199012346',addresses:[{id:'a',line:'Calle 2'}],points:9999},200);
 await status('new','users/auth-new','PUT',{name:'New',phone:'99990001',dni:'0801199012346',addresses:[{id:'a',line:'Calle 2'}],points:9999},200);
 assert.equal(state.users['auth-new'].points,500);
 await status('invalid','orders','GET',undefined,401);
 await status('admin','media/test','PUT','data:image/svg+xml;base64,PHN2Zz4=',400);
 state.products.t={id:'torta-mexicana',name:'Torta mexicana',price:110,available:true,modifiers:[]};
 const redeem={items:[{productId:'torta-mexicana',qty:1}],total:0,payment:'Efectivo',address:'Calle 1',redeemPts:1100};
 await status('alice','orders/r1','PUT',redeem,200);
 await status('alice','orders/r1','PUT',redeem,200);
 assert.equal(state.users['auth-alice'].points,1130);
 await status('alice','orders/r2','PUT',redeem,200);
 await status('alice','orders/r3','PUT',redeem,409);
 assert.equal(state.users['auth-alice'].points,30);
 Object.assign(context,await import('../server/shift-maintenance.js'),await import('../server/instance.js'));
 // Exercise the actual status handler, including the unpaid delivery barrier.
 context.mockDb=db;context.mockMutate=mutateDb;context.mockVerify=verifyFirebaseUser;context.mockJson=json;
 context.createDelivery=()=>({});
 context.createFamily=()=>({route:async()=>json({})});
 context.createPayerGame=()=>({route:async()=>json({})});
 context.createChupisticaGame=()=>({route:async()=>json({})});
 context.createManager=()=>({recordSale:async()=>({})});
 vm.runInContext(read('_worker.js').replace(/^(?:import .*\n)+/,'').replace('export default {','globalThis.worker={'),context);
 vm.runInContext('db=mockDb;mutateDb=mockMutate;verifyFirebaseUser=mockVerify;access.award=async()=>{};',context);
 const invoiceRequest=(who,id,payment,shiftId,payWith=0)=>new Request('https://test.local/api/invoice-order',{method:'POST',headers:{Authorization:'Bearer '+who},body:JSON.stringify({id,payment,shiftId,payWith})});
 state.roles.cash2='cashier';state.users['auth-cash2']={id:'auth-cash2',role:'cashier'};state.shifts.s2={id:'s2',userId:'auth-cash2'};
 state.orders.shared={...clone(state.orders.r1),id:'shared',status:'preparacion',paidAt:'',invoiced:false,total:110};
 let invoiced=await context.invoiceOrderSecure(invoiceRequest('cash','shared','Tarjeta','s1'),{});
 assert.equal(invoiced.status,200);assert.equal(state.orders.shared.paymentChannel,'pos');assert.equal(state.orders.shared.paidBy,'auth-cash');assert.equal(state.orders.shared.invoiced,true);
 invoiced=await context.invoiceOrderSecure(invoiceRequest('cash2','shared','Tarjeta','s2'),{});
 assert.equal(invoiced.status,200);assert.equal((await invoiced.json()).alreadyInvoiced,true);assert.equal(state.orders.shared.paymentChannel,'pos');assert.equal(state.orders.shared.paidBy,'auth-cash');
 state.orders.legacy={...clone(state.orders.r1),id:'legacy',status:'entregado',paidAt:'',invoiced:false,total:110};
 invoiced=await context.invoiceOrderSecure(invoiceRequest('cash2','legacy','Efectivo','s2',110),{});
 assert.equal(invoiced.status,200);assert.equal(state.orders.legacy.invoiced,true);assert.equal(state.orders.legacy.paidBy,'auth-cash2');
 state.orders.cashDelivery={...clone(state.orders.r1),id:'cashDelivery',type:'delivery',status:'listo',payment:'Efectivo',paidAt:'',invoiced:false,total:110};
 invoiced=await context.invoiceOrderSecure(invoiceRequest('cash','cashDelivery','Efectivo','s1',200),{});
 assert.equal(invoiced.status,200);assert.equal(state.orders.cashDelivery.needsChange,true);assert.equal(state.orders.cashDelivery.cashReceivedFrom,'driver');assert.equal(state.orders.cashDelivery.changeGiven,90);
 await status('cash','orders/zeroNew','PUT',{...order,payment:'Efectivo',paidAt:'yes',shiftId:'s1',payWith:0},400);
 assert.equal(state.orders.zeroNew,undefined);
 state.orders.zeroCash={...clone(state.orders.r1),id:'zeroCash',status:'listo',paidAt:'',invoiced:false,total:110};
 await assert.rejects(()=>context.invoiceOrderSecure(invoiceRequest('cash','zeroCash','Efectivo','s1',0),{}),/no cubre/);
 assert.equal(state.orders.zeroCash.invoiced,false);
 state.orders.exactCash={...clone(state.orders.zeroCash),id:'exactCash'};
 assert.equal((await context.invoiceOrderSecure(invoiceRequest('cash','exactCash','Efectivo','s1',110),{})).status,200);
 assert.equal(state.orders.exactCash.changeGiven,0);
 state.orders.transfer={...clone(state.orders.zeroCash),id:'transfer'};
 assert.equal((await context.invoiceOrderSecure(invoiceRequest('cash','transfer','Transferencia','s1',0),{})).status,200);
 assert.equal(state.orders.transfer.payWith,0);
 const request=(who,id,status)=>new Request('https://test.local/api/order-status',{method:'POST',headers:{Authorization:'Bearer '+who},body:JSON.stringify({id,status})});
 const unpaid=clone(state.orders.r1);unpaid.id='delivery';state.orders.delivery=unpaid;
 assert.equal((await context.changeOrderStatus(request('cash','delivery','entregado'),{})).status,409);
 assert.equal(state.orders.delivery.status,'nuevo');
 state.deliveries={delivery:{id:'delivery',orderId:'delivery',status:'delivered'}};
 assert.equal((await context.changeOrderStatus(request('cash','delivery','entregado'),{})).status,409);
 assert.equal(state.orders.delivery.status,'nuevo');
 assert.equal((await context.changeOrderStatus(request('cook','delivery','entregado'),{})).status,403);
 assert.equal((await context.changeOrderStatus(request('cook','delivery','listo'),{})).status,200);
 assert.equal(state.orders.delivery.status,'listo');
 const app=read('js/app.js');
 assert.match(app,/new Date\(o\.scheduledFor\)\.getTime\(\) <= now/);
 assert.match(app,/kds-customer/);assert.match(app,/data-order-cal-day/);
 console.log('PASS: roles, órdenes del día, calendario, KDS, facturación multiempleado atómica, regularización, pagos y puntos.');
})().catch(e=>{console.error(e);process.exitCode=1;});
