const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
  const ctx={};vm.runInNewContext(fs.readFileSync('js/hours.js','utf8'),ctx);
  vm.runInNewContext(fs.readFileSync('js/data.js','utf8')+';globalThis.settings=SEED_SETTINGS;',ctx);
  const hours=ctx.ChingadazoHours,s=ctx.settings;s.open=true;
  const at=text=>new Date(text+'-06:00');
  assert(hours.validate(s.weeklyHours));
  assert(!hours.active(s,at('2026-09-28T15:00:00')),'Monday closed');
  assert(!hours.active(s,at('2026-09-29T12:59:00')));
  assert(hours.active(s,at('2026-09-29T13:00:00')));
  assert(!hours.active(s,at('2026-09-29T22:00:00')));
  assert(hours.active(s,at('2026-10-02T23:59:00')));
  assert(!hours.active(s,at('2026-10-03T00:00:00')));
  s.weeklyHours[5].close='01:30';
  assert(hours.active(s,at('2026-10-03T01:29:00')),'Friday extension belongs to Saturday morning');
  assert(!hours.active(s,at('2026-10-03T01:30:00')));
  assert(hours.active(s,at('2026-10-04T21:59:00')));assert(!hours.active(s,at('2026-10-04T22:00:00')));
  assert.equal(hours.next(s,at('2026-09-27T22:00:00')),at('2026-09-29T13:00:00').getTime());
  const bad=structuredClone(s.weeklyHours);bad[2].close='13:00';assert(!hours.validate(bad));
  bad[2].close='25:00';assert(!hours.validate(bad));
  const {createAccess}=await import('../server/access.js');
  const state={settings:s,products:{p:{id:'p',name:'Prueba',price:10}},users:{u:{name:'Prueba'}}};
  const db=async(_env,path,init)=>{if(init){state[path.slice(1)]=JSON.parse(init.body);return state[path.slice(1)]}return path.split('/').filter(Boolean).reduce((v,k)=>v?.[k],state);};
  const access=createAccess({db,schedule:hours,mutateDb:async()=>{},verifyFirebaseUser:async()=>({localId:'admin'}),json:x=>Response.json(x)});
  const publicSettings=await(await access.route(new Request('https://test/api/data/settings'),{})).json();
  assert.deepEqual(publicSettings.weeklyHours,JSON.parse(JSON.stringify(s.weeklyHours)));
  s.open=false;
  await assert.rejects(access.createOrder({}, {role:'customer',id:'u',user:{}},'o',{items:[{productId:'p',qty:1}],type:'pickup'}),/pausados/);
  console.log('PASS editable weekly hours, Monday closure, Sunday, midnight, event extension, next opening and server pause.');
})().catch(e=>{console.error(e);process.exitCode=1});
